/**
 * Generates src/data/franceOutline.ts: the outline of metropolitan France
 * (mainland, Corsica and the islands pilots fly to: Ouessant, Belle-Île, Yeu,
 * Ré, Oléron…), projected to Lambert-93, scaled to a 1000-unit-wide SVG frame
 * and simplified for that size.
 *
 * Source: Natural Earth 1:10m admin-0 countries (public domain). Rerun only to
 * change the resolution or the frame:
 *
 *   npx tsx scripts/build-france-outline.ts
 */
import { writeFileSync } from 'node:fs'
import { lambert93 } from '../src/utils/franceMap.ts'

const SOURCE = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_0_countries.geojson'
const WIDTH = 1000
/** Douglas-Peucker tolerance, in frame units (≈ 1 km each) */
const TOLERANCE = 0.5
/** Islands smaller than this (frame units²) are dropped; Ouessant is ≈ 15 */
const MIN_AREA = 6
// Metropolitan France only: drops overseas territories from the same feature.
const inMetropole = ([lon, lat]: number[]) => lon > -6 && lon < 10 && lat > 41 && lat < 52

type Point = [number, number]

const simplify = (points: Point[], tolerance: number): Point[] => {
  if (points.length < 3) return points
  const [ax, ay] = points[0]
  const [bx, by] = points[points.length - 1]
  const length = Math.hypot(bx - ax, by - ay)
  let index = 0
  let max = 0
  for (let i = 1; i < points.length - 1; i++) {
    const [px, py] = points[i]
    const d = length === 0
      ? Math.hypot(px - ax, py - ay)
      : Math.abs((bx - ax) * (ay - py) - (ax - px) * (by - ay)) / length
    if (d > max) { max = d; index = i }
  }
  if (max <= tolerance) return [points[0], points[points.length - 1]]
  return [...simplify(points.slice(0, index + 1), tolerance).slice(0, -1), ...simplify(points.slice(index), tolerance)]
}

const area = (ring: Point[]) =>
  Math.abs(ring.reduce((sum, [x, y], i) => {
    const [nx, ny] = ring[(i + 1) % ring.length]
    return sum + x * ny - nx * y
  }, 0)) / 2

const geojson = await (await fetch(SOURCE)).json()
const france = geojson.features.find((f: { properties: { ADM0_A3: string } }) => f.properties.ADM0_A3 === 'FRA')
const polygons: number[][][][] = france.geometry.type === 'MultiPolygon' ? france.geometry.coordinates : [france.geometry.coordinates]
const rings = polygons.map((p) => p[0]).filter((ring) => ring.every(inMetropole))

const projected = rings.map((ring) => ring.map(([lon, lat]) => lambert93(lat, lon)))
const xs = projected.flat().map(([x]) => x)
const ys = projected.flat().map(([, y]) => y)
const minX = Math.min(...xs)
const maxY = Math.max(...ys)
const scale = WIDTH / (Math.max(...xs) - minX)
const height = Math.ceil((maxY - Math.min(...ys)) * scale)

const framed = projected
  .map((ring) => ring.map(([x, y]): Point => [(x - minX) * scale, (maxY - y) * scale]))
  .filter((ring) => area(ring) >= MIN_AREA)
  .map((ring) => simplify(ring, TOLERANCE))

const r = (v: number) => Math.round(v * 10) / 10
const path = framed.map((ring) => 'M' + ring.map(([x, y]) => `${r(x)} ${r(y)}`).join('L') + 'Z').join('')

writeFileSync('src/data/franceOutline.ts', `// Generated by scripts/build-france-outline.ts — do not edit.
// Metropolitan France from Natural Earth 1:10m (public domain), Lambert-93.
import type { MapFrame } from '../utils/franceMap'

export const FRANCE_WIDTH = ${WIDTH}
export const FRANCE_HEIGHT = ${height}
export const FRANCE_FRAME: MapFrame = { minX: ${minX}, maxY: ${maxY}, scale: ${scale} }
export const FRANCE_PATH = '${path}'
`)
console.log(`${rings.length} rings -> ${framed.length} kept, ${framed.flat().length} points, ${WIDTH}x${height}, ${path.length} chars`)
